name: project
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  another_flushbar: ^1.10.24
  dio: ^3.0.10
  youtube_player_flutter: ^8.0.0
  carousel_slider: ^4.0.0
  flutter_barcode_scanner: ^1.0.2
  barcode_widget: ^2.0.0
  share: ^2.0.4
  flutter_tts: ^1.2.3
  shared_preferences: ^2.0.7
  image_picker: ^0.6.7+21
  google_maps_flutter: ^1.0.1
  url_launcher: ^6.0.3
  location: ^3.2.4
  flutter_rating_bar: ^4.0.0
  multi_image_picker: ^4.1.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  assets:
    - assets/images/pin_marker.png
    - assets/images/pin_biker.png
    - assets/images/cinema.png
    - assets/images/map.png
    - assets/images/mini.jpg
    - assets/images/newspaper.png
    - assets/images/no_photo.png
    - assets/images/leaf.jpg
    - assets/images/search.png
    - assets/images/qr-scan.png
    - assets/images/qr-gen.png
    - assets/images/TA.png
    - assets/images/TA1.png
    - assets/images/MCondo.jpg
    - assets/images/apartment.png
    - assets/images/condominium.png
    - assets/images/house.png
    - assets/images/cond5.png
    - assets/images/map1.png
    - assets/images/py.jpg
    - assets/images/F.jpg
    - assets/images/il.JPG
    - assets/images/1A.jpg
    - assets/images/11.jpg
    - assets/images/pricing.png
    - assets/images/hh1.png




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
